/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#6063ee",
        "primary-container": "#1e293b",
        "tertiary-fixed": "#ffdf9e",
        "ink-muted": "#94a3b8",
        "on-primary-container": "#8590a6",
        "primary-fixed": "#d8e3fb",
        "surface-container": "#1e293b",
        "surface-variant": "#334155",
        "background": "#091426",
        "primary": "#091426",
        "surface-bright": "#0f172a",
        "on-primary-fixed": "#111c2d",
        "on-tertiary-container": "#b68900",
        "ink-dark": "#f8fafc",
        "on-tertiary-fixed-variant": "#5b4300",
        "on-primary-fixed-variant": "#3c475a",
        "on-surface": "#f8fafc",
        "accent-purple": "#A78BFA",
        "secondary": "#818cf8",
        "primary-fixed-dim": "#bcc7de",
        "surface-tint": "#545f73",
        "on-secondary-container": "#fffbff",
        "outline": "#75777d",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "error": "#fb7185",
        "inverse-on-surface": "#0f172a",
        "on-tertiary-fixed": "#261a00",
        "surface-dim": "#0f172a",
        "surface-container-highest": "#334155",
        "inverse-primary": "#bcc7de",
        "on-background": "#f8fafc",
        "error-container": "#4c0519",
        "outline-variant": "#334155",
        "on-secondary-fixed": "#07006c",
        "tertiary-fixed-dim": "#f9bd15",
        "surface-container-high": "#1e293b",
        "on-error-container": "#ffdad6",
        "surface": "#091426",
        "on-surface-variant": "#94a3b8",
        "tertiary": "#1c1300",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "success-green": "#34d399",
        "surface-container-lowest": "#020617",
        "tertiary-container": "#362600",
        "surface-white": "#0f172a",
        "on-error": "#ffffff",
        "surface-container-low": "#0f172a",
        "inverse-surface": "#f8fafc",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e1e0ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "card": "24px"
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
